CREATE DATABASE hotel DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
CREATE TABLE `hotel`.`user_t` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_name` VARCHAR(45) NULL,
  `load_name` VARCHAR(45) NULL,
  `password` VARCHAR(45) NULL,
  `age` INT NULL,
  PRIMARY KEY (`id`))ENGINE=MyISAM AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;